### ISSUE TITLE
Persistent indexdb storage

### ISSUE THREAD

**Issue by nullset** [IBM/browser-functions#15]
I'm attempting to leverage the in-browser indexdb storage to store some arbitrary data. Ideally this data would be persisted across any necessary restarts of the app. While I'm able to store data to indexdb, this data seems to be cleared upon any server restart. Is it possible to make this data persistent across restarts? 

Thanks!

**Comment by tobykurien** [comment]
This happens because server is creating incognito browsers:

https://github.com/IBM/browser-functions/blob/master/server/admin.js#L134

However, I would advise against relying on browser local storage because it won't work when you need to spin up more than one browser instance, thus limiting scalability. Rather use an external data store, like in this example:

https://github.com/IBM/browser-functions/blob/master/functions_root/examples/files/storage/hitcounter.js

**Comment by richardyoung00** [comment]
It should be possible by manually specifying a browser profile directory`--user-data-dir=/path/to/foo` for Chrome or `-profile /path/to/foo` for Firefox. Add these to the args passed to the browser in admin.js

**Comment by tobykurien** [comment]
If you still prefer to store data in the browser (and forgo scalability), one solution is to spin up your own browser that will store your data, and set your app to use this user browser rather than the server-created browsers. That way all executions will run in your browser instance.

**Comment by nullset** [comment]
Great thank you for the information. I figured that using indexdb in this manner would limit scalability, for my purposes this shouldn't be an issue.

**Comment by jimmywarting** [comment]
> It should be possible by manually specifying a browser profile directory`--user-data-dir=/path/to/foo` for Chrome or `-profile /path/to/foo` for Firefox. Add these to the args passed to the browser in admin.js

I think that would be a grate idea!

I would also like to try out browsers own storage.
I would even want to try out if a server can have web push. so i can push stuff to it without it even being online.
Messages would get queued up by firebase cloud message if they aren't delivered...
I would also want to get a FileSystemDirectoryHandle from [native file system access](https://wicg.github.io/native-file-system/), store it in indexedDB and have read/write access to a selected directory.

so i got a other question: how do you deal with premission request?
like: `navigator.geolocation.getCurrentPosition(console.log)`

**Comment by richardyoung00** [comment]
> so i got a other question: how do you deal with premission request?
like: navigator.geolocation.getCurrentPosition(console.log)

The current implementation doesn't handle permission requests. One option would be to override the `navigator.geolocation.getCurrentPosition` function in `templates/app.js`. You could also look at sending a CDP command to the browser to enable geolocation for a site and manually set the coordinates.
